import os
import re

# 文档标题映射
titles = {
    # 前端基础
    'frontend/basics/web-intro': 'Web 开发概述',
    'frontend/basics/dev-environment': '开发环境搭建',
    'frontend/basics/browser-devtools': '浏览器开发者工具使用指南',
    'frontend/basics/vscode-setup': 'VS Code 编辑器配置',
    # HTML
    'frontend/html/01-intro': 'HTML 简介与文档结构',
    'frontend/html/02-text-elements': 'HTML 文本元素',
    'frontend/html/03-links-images': 'HTML 链接与图片',
    'frontend/html/04-tables': 'HTML 表格',
    'frontend/html/05-forms': 'HTML 表单基础',
    'frontend/html/06-form-validation': 'HTML 表单验证',
    'frontend/html/07-semantic-tags': 'HTML5 语义化标签',
    'frontend/html/08-multimedia': 'HTML 多媒体元素',
    'frontend/html/09-canvas-basics': 'Canvas 画布基础',
    'frontend/html/10-svg-basics': 'SVG 矢量图形基础',
    'frontend/html/11-accessibility': 'Web 无障碍访问',
    # CSS 基础
    'frontend/css/basics/01-intro': 'CSS 简介与引入方式',
    'frontend/css/basics/02-selectors': 'CSS 选择器详解',
    'frontend/css/basics/03-specificity': 'CSS 优先级与层叠',
    'frontend/css/basics/04-box-model': 'CSS 盒模型',
    'frontend/css/basics/05-colors-units': 'CSS 颜色与单位',
    'frontend/css/basics/06-text-fonts': 'CSS 文本与字体样式',
    'frontend/css/basics/07-backgrounds': 'CSS 背景样式',
    # CSS 布局
    'frontend/css/layout/01-display': 'CSS display 属性',
    'frontend/css/layout/02-position': 'CSS 定位详解',
    'frontend/css/layout/03-float': 'CSS 浮动布局',
    'frontend/css/layout/04-flexbox': 'Flexbox 弹性布局',
    'frontend/css/layout/05-flexbox-practice': 'Flexbox 实战练习',
    'frontend/css/layout/06-grid': 'CSS Grid 网格布局',
    'frontend/css/layout/07-grid-practice': 'Grid 布局实战',
    'frontend/css/layout/08-multi-column': 'CSS 多列布局',
}

# CSS 响应式
titles.update({
    'frontend/css/responsive/01-media-queries': 'CSS 媒体查询',
    'frontend/css/responsive/02-mobile-first': '移动优先设计',
    'frontend/css/responsive/03-viewport': '视口与响应式单位',
    'frontend/css/responsive/04-responsive-images': '响应式图片',
    # CSS 高级
    'frontend/css/advanced/01-transitions': 'CSS 过渡动画',
    'frontend/css/advanced/02-animations': 'CSS 关键帧动画',
    'frontend/css/advanced/03-transforms': 'CSS 变换',
    'frontend/css/advanced/04-variables': 'CSS 自定义属性',
    'frontend/css/advanced/05-calc-functions': 'CSS 计算函数',
    'frontend/css/advanced/06-pseudo-elements': 'CSS 伪元素',
    'frontend/css/practice/01-common-layouts': '常见布局实现',
    'frontend/css/practice/02-component-styles': '组件样式设计',
    'frontend/css/practice/03-css-reset': 'CSS 重置与规范化',
    # JavaScript 基础
    'frontend/javascript/basics/01-intro': 'JavaScript 简介',
    'frontend/javascript/basics/02-variables': '变量与数据类型',
    'frontend/javascript/basics/03-operators': '运算符',
    'frontend/javascript/basics/04-conditionals': '条件语句',
    'frontend/javascript/basics/05-loops': '循环语句',
    'frontend/javascript/basics/06-functions': '函数基础',
    'frontend/javascript/basics/07-scope': '作用域与闭包',
    'frontend/javascript/basics/08-arrays': '数组操作',
    'frontend/javascript/basics/09-objects': '对象基础',
    'frontend/javascript/basics/10-strings': '字符串处理',
    # JavaScript ES6
    'frontend/javascript/es6/01-let-const': 'let 与 const',
    'frontend/javascript/es6/02-arrow-functions': '箭头函数',
    'frontend/javascript/es6/03-template-literals': '模板字符串',
    'frontend/javascript/es6/04-destructuring': '解构赋值',
    'frontend/javascript/es6/05-spread-rest': '展开与剩余运算符',
    'frontend/javascript/es6/06-classes': 'ES6 类',
    'frontend/javascript/es6/07-modules': 'ES6 模块化',
    'frontend/javascript/es6/08-symbols': 'Symbol 类型',
    'frontend/javascript/es6/09-iterators': '迭代器与生成器',
    'frontend/javascript/es6/10-map-set': 'Map 与 Set',
    'frontend/javascript/es6/11-proxy-reflect': 'Proxy 与 Reflect',
})

# JavaScript DOM 和异步
titles.update({
    'frontend/javascript/dom/01-dom-intro': 'DOM 简介',
    'frontend/javascript/dom/02-selecting': 'DOM 元素选择',
    'frontend/javascript/dom/03-manipulation': 'DOM 操作',
    'frontend/javascript/dom/04-events': '事件处理',
    'frontend/javascript/dom/05-event-delegation': '事件委托',
    'frontend/javascript/dom/06-forms': '表单处理',
    'frontend/javascript/dom/07-bom': 'BOM 浏览器对象',
    'frontend/javascript/async/01-callbacks': '回调函数',
    'frontend/javascript/async/02-promises': 'Promise 基础',
    'frontend/javascript/async/03-promise-methods': 'Promise 方法',
    'frontend/javascript/async/04-async-await': 'async/await',
    'frontend/javascript/async/05-fetch-api': 'Fetch API',
    'frontend/javascript/async/06-error-handling': '异步错误处理',
    'frontend/javascript/async/07-event-loop': '事件循环机制',
    'frontend/javascript/advanced/01-this': 'this 关键字',
    'frontend/javascript/advanced/02-prototype': '原型与原型链',
    'frontend/javascript/advanced/03-inheritance': '继承模式',
    'frontend/javascript/advanced/04-execution-context': '执行上下文',
    'frontend/javascript/advanced/05-memory': '内存管理',
    'frontend/javascript/advanced/06-regexp': '正则表达式',
    'frontend/javascript/advanced/07-design-patterns': 'JS 设计模式',
    'frontend/javascript/practice/01-debugging': '调试技巧',
    'frontend/javascript/practice/02-performance': '性能优化',
    'frontend/javascript/practice/03-best-practices': '最佳实践',
    # TypeScript
    'frontend/typescript/basics/01-intro': 'TypeScript 简介',
    'frontend/typescript/basics/02-setup': 'TypeScript 环境搭建',
    'frontend/typescript/basics/03-basic-types': '基础类型',
    'frontend/typescript/basics/04-type-inference': '类型推断',
    'frontend/typescript/basics/05-interfaces': '接口',
    'frontend/typescript/basics/06-type-aliases': '类型别名',
    'frontend/typescript/basics/07-union-intersection': '联合与交叉类型',
    'frontend/typescript/advanced/01-generics': '泛型基础',
    'frontend/typescript/advanced/02-generic-constraints': '泛型约束',
    'frontend/typescript/advanced/03-utility-types': '工具类型',
    'frontend/typescript/advanced/04-conditional-types': '条件类型',
    'frontend/typescript/advanced/05-mapped-types': '映射类型',
    'frontend/typescript/advanced/06-decorators': '装饰器',
    'frontend/typescript/advanced/07-declaration-files': '声明文件',
    'frontend/typescript/practice/01-with-react': 'TypeScript + React',
    'frontend/typescript/practice/02-with-vue': 'TypeScript + Vue',
    'frontend/typescript/practice/03-config': 'tsconfig 配置',
})

# React
titles.update({
    'frontend/react/basics/01-intro': 'React 简介',
    'frontend/react/basics/02-create-app': '创建 React 应用',
    'frontend/react/basics/03-jsx': 'JSX 语法',
    'frontend/react/basics/04-components': '组件基础',
    'frontend/react/basics/05-props': 'Props 属性传递',
    'frontend/react/basics/06-state': 'State 状态管理',
    'frontend/react/basics/07-events': '事件处理',
    'frontend/react/basics/08-conditional': '条件渲染',
    'frontend/react/basics/09-lists': '列表渲染',
    'frontend/react/basics/10-forms': '表单处理',
    'frontend/react/hooks/01-useState': 'useState Hook',
    'frontend/react/hooks/02-useEffect': 'useEffect Hook',
    'frontend/react/hooks/03-useContext': 'useContext Hook',
    'frontend/react/hooks/04-useRef': 'useRef Hook',
    'frontend/react/hooks/05-useMemo': 'useMemo Hook',
    'frontend/react/hooks/06-useCallback': 'useCallback Hook',
    'frontend/react/hooks/07-useReducer': 'useReducer Hook',
    'frontend/react/hooks/08-custom-hooks': '自定义 Hook',
    'frontend/react/hooks/09-hooks-rules': 'Hooks 使用规则',
    'frontend/react/router/01-intro': 'React Router 简介',
    'frontend/react/router/02-nested-routes': '嵌套路由',
    'frontend/react/router/03-params': '路由参数',
    'frontend/react/router/04-navigation': '编程式导航',
    'frontend/react/router/05-guards': '路由守卫',
    'frontend/react/state/01-state-lifting': '状态提升',
    'frontend/react/state/02-redux-intro': 'Redux 简介',
    'frontend/react/state/03-redux-toolkit': 'Redux Toolkit',
    'frontend/react/state/04-zustand': 'Zustand 状态管理',
    'frontend/react/state/05-jotai': 'Jotai 原子化状态',
    'frontend/react/advanced/01-lifecycle': '生命周期',
    'frontend/react/advanced/02-context': 'Context API',
    'frontend/react/advanced/03-hoc': '高阶组件',
    'frontend/react/advanced/04-render-props': 'Render Props',
    'frontend/react/advanced/05-portals': 'Portals',
    'frontend/react/advanced/06-error-boundaries': '错误边界',
    'frontend/react/advanced/07-suspense': 'Suspense',
    'frontend/react/advanced/08-server-components': '服务端组件',
    'frontend/react/practice/01-project-structure': '项目结构',
    'frontend/react/practice/02-styling': '样式方案',
    'frontend/react/practice/03-testing': '测试',
    'frontend/react/practice/04-performance': '性能优化',
})

# Vue
titles.update({
    'frontend/vue/basics/01-intro': 'Vue 简介',
    'frontend/vue/basics/02-create-app': '创建 Vue 应用',
    'frontend/vue/basics/03-template': '模板语法',
    'frontend/vue/basics/04-directives': '指令',
    'frontend/vue/basics/05-computed': '计算属性',
    'frontend/vue/basics/06-watchers': '侦听器',
    'frontend/vue/basics/07-class-style': '类与样式绑定',
    'frontend/vue/basics/08-conditional': '条件渲染',
    'frontend/vue/basics/09-lists': '列表渲染',
    'frontend/vue/basics/10-events': '事件处理',
    'frontend/vue/components/01-basics': '组件基础',
    'frontend/vue/components/02-props': 'Props',
    'frontend/vue/components/03-emits': '自定义事件',
    'frontend/vue/components/04-slots': '插槽',
    'frontend/vue/components/05-provide-inject': 'Provide/Inject',
    'frontend/vue/components/06-dynamic': '动态组件',
    'frontend/vue/components/07-async': '异步组件',
    'frontend/vue/composition/01-setup': 'setup 函数',
    'frontend/vue/composition/02-ref-reactive': 'ref 与 reactive',
    'frontend/vue/composition/03-computed-watch': 'computed 与 watch',
    'frontend/vue/composition/04-lifecycle': '生命周期钩子',
    'frontend/vue/composition/05-composables': '组合式函数',
    'frontend/vue/composition/06-script-setup': 'script setup',
    'frontend/vue/router/01-intro': 'Vue Router 简介',
    'frontend/vue/router/02-routes': '路由配置',
    'frontend/vue/router/03-params': '路由参数',
    'frontend/vue/router/04-guards': '导航守卫',
    'frontend/vue/router/05-lazy-loading': '路由懒加载',
    'frontend/vue/state/01-pinia-intro': 'Pinia 简介',
    'frontend/vue/state/02-pinia-state': 'State 状态',
    'frontend/vue/state/03-pinia-getters': 'Getters',
    'frontend/vue/state/04-pinia-actions': 'Actions',
    'frontend/vue/state/05-pinia-plugins': 'Pinia 插件',
    'frontend/vue/practice/01-project-structure': '项目结构',
    'frontend/vue/practice/02-styling': '样式方案',
    'frontend/vue/practice/03-performance': '性能优化',
})

# 前端工程化
titles.update({
    'frontend/engineering/package-managers/01-npm': 'npm 包管理器',
    'frontend/engineering/package-managers/02-yarn': 'Yarn 包管理器',
    'frontend/engineering/package-managers/03-pnpm': 'pnpm 包管理器',
    'frontend/engineering/build-tools/01-webpack-intro': 'Webpack 简介',
    'frontend/engineering/build-tools/02-webpack-config': 'Webpack 配置',
    'frontend/engineering/build-tools/03-webpack-loaders': 'Webpack Loaders',
    'frontend/engineering/build-tools/04-webpack-plugins': 'Webpack Plugins',
    'frontend/engineering/build-tools/05-webpack-optimize': 'Webpack 优化',
    'frontend/engineering/build-tools/06-vite-intro': 'Vite 简介',
    'frontend/engineering/build-tools/07-vite-config': 'Vite 配置',
    'frontend/engineering/build-tools/08-rollup': 'Rollup 打包',
    'frontend/engineering/code-quality/01-eslint': 'ESLint 代码检查',
    'frontend/engineering/code-quality/02-prettier': 'Prettier 代码格式化',
    'frontend/engineering/code-quality/03-husky': 'Husky Git Hooks',
    'frontend/engineering/code-quality/04-lint-staged': 'lint-staged',
    'frontend/engineering/testing/01-jest-intro': 'Jest 测试框架',
    'frontend/engineering/testing/02-unit-testing': '单元测试',
    'frontend/engineering/testing/03-vitest': 'Vitest 测试',
    'frontend/engineering/testing/04-testing-library': 'Testing Library',
    'frontend/engineering/testing/05-e2e-cypress': 'Cypress E2E 测试',
    'frontend/engineering/deployment/01-build': '构建与打包',
    'frontend/engineering/deployment/02-cdn': 'CDN 部署',
    'frontend/engineering/deployment/03-ci-cd': 'CI/CD 流程',
    # 前端进阶
    'frontend/advanced/performance/01-metrics': '性能指标',
    'frontend/advanced/performance/02-loading': '加载优化',
    'frontend/advanced/performance/03-rendering': '渲染优化',
    'frontend/advanced/performance/04-caching': '缓存策略',
    'frontend/advanced/performance/05-monitoring': '性能监控',
    'frontend/advanced/security/01-xss': 'XSS 攻击防御',
    'frontend/advanced/security/02-csrf': 'CSRF 攻击防御',
    'frontend/advanced/security/03-https': 'HTTPS 安全',
    'frontend/advanced/ssr/01-intro': '服务端渲染简介',
    'frontend/advanced/ssr/02-nextjs': 'Next.js',
    'frontend/advanced/ssr/03-nuxt': 'Nuxt.js',
    'frontend/advanced/ssr/04-ssg': '静态站点生成',
    'frontend/advanced/pwa/01-intro': 'PWA 简介',
    'frontend/advanced/pwa/02-service-worker': 'Service Worker',
    'frontend/advanced/pwa/03-manifest': 'Web App Manifest',
    'frontend/advanced/micro-frontend/01-intro': '微前端简介',
    'frontend/advanced/micro-frontend/02-qiankun': 'qiankun 框架',
    'frontend/advanced/micro-frontend/03-module-federation': '模块联邦',
})

# 后端基础和 Java
titles.update({
    'backend/basics/01-intro': '后端开发概述',
    'backend/basics/02-http': 'HTTP 协议详解',
    'backend/basics/03-restful': 'RESTful API 设计',
    'backend/basics/04-api-design': 'API 设计规范',
    'backend/basics/05-authentication': '身份认证机制',
    'backend/java/basics/01-intro': 'Java 简介',
    'backend/java/basics/02-setup': 'Java 环境搭建',
    'backend/java/basics/03-syntax': 'Java 基础语法',
    'backend/java/basics/04-data-types': 'Java 数据类型',
    'backend/java/basics/05-operators': 'Java 运算符',
    'backend/java/basics/06-control-flow': 'Java 流程控制',
    'backend/java/basics/07-arrays': 'Java 数组',
    'backend/java/basics/08-methods': 'Java 方法',
    'backend/java/basics/09-strings': 'Java 字符串',
    'backend/java/oop/01-classes': 'Java 类与对象',
    'backend/java/oop/02-encapsulation': '封装',
    'backend/java/oop/03-inheritance': '继承',
    'backend/java/oop/04-polymorphism': '多态',
    'backend/java/oop/05-abstraction': '抽象类与接口',
    'backend/java/oop/06-inner-classes': '内部类',
    'backend/java/oop/07-enums': '枚举类型',
    'backend/java/advanced/01-exceptions': '异常处理',
    'backend/java/advanced/02-generics': '泛型',
    'backend/java/advanced/03-collections': '集合框架',
    'backend/java/advanced/04-streams': 'Stream API',
    'backend/java/advanced/05-lambda': 'Lambda 表达式',
    'backend/java/advanced/06-io': 'IO 流',
    'backend/java/advanced/07-nio': 'NIO',
    'backend/java/advanced/08-multithreading': '多线程基础',
    'backend/java/advanced/09-concurrency': '并发编程',
    'backend/java/advanced/10-reflection': '反射机制',
    'backend/java/advanced/11-annotations': '注解',
    'backend/java/jvm/01-architecture': 'JVM 架构',
    'backend/java/jvm/02-memory': 'JVM 内存模型',
    'backend/java/jvm/03-gc': '垃圾回收',
    'backend/java/jvm/04-classloader': '类加载机制',
    'backend/java/jvm/05-tuning': 'JVM 调优',
})

# Java Spring 和工具
titles.update({
    'backend/java/spring/01-intro': 'Spring 框架简介',
    'backend/java/spring/02-ioc': 'IoC 控制反转',
    'backend/java/spring/03-di': '依赖注入',
    'backend/java/spring/04-aop': 'AOP 面向切面编程',
    'backend/java/spring/05-beans': 'Bean 管理',
    'backend/java/springboot/01-intro': 'Spring Boot 简介',
    'backend/java/springboot/02-quickstart': '快速开始',
    'backend/java/springboot/03-configuration': '配置管理',
    'backend/java/springboot/04-controllers': '控制器',
    'backend/java/springboot/05-services': '服务层',
    'backend/java/springboot/06-repositories': '数据访问层',
    'backend/java/springboot/07-validation': '数据验证',
    'backend/java/springboot/08-exception': '异常处理',
    'backend/java/springboot/09-security': 'Spring Security',
    'backend/java/springboot/10-actuator': 'Actuator 监控',
    'backend/java/springboot/11-testing': '测试',
    'backend/java/mybatis/01-intro': 'MyBatis 简介',
    'backend/java/mybatis/02-configuration': 'MyBatis 配置',
    'backend/java/mybatis/03-mapper': 'Mapper 映射',
    'backend/java/mybatis/04-dynamic-sql': '动态 SQL',
    'backend/java/mybatis/05-cache': '缓存机制',
    'backend/java/mybatis/06-mybatis-plus': 'MyBatis-Plus',
    'backend/java/tools/01-maven': 'Maven 构建工具',
    'backend/java/tools/02-gradle': 'Gradle 构建工具',
    'backend/java/tools/03-junit': 'JUnit 单元测试',
})

# Node.js
titles.update({
    'backend/nodejs/basics/01-intro': 'Node.js 简介',
    'backend/nodejs/basics/02-setup': 'Node.js 环境搭建',
    'backend/nodejs/basics/03-modules': '模块系统',
    'backend/nodejs/basics/04-npm': 'npm 包管理',
    'backend/nodejs/basics/05-fs': '文件系统模块',
    'backend/nodejs/basics/06-path': 'path 路径模块',
    'backend/nodejs/basics/07-events': '事件模块',
    'backend/nodejs/basics/08-streams': '流',
    'backend/nodejs/basics/09-buffer': 'Buffer 缓冲区',
    'backend/nodejs/basics/10-process': '进程管理',
    'backend/nodejs/http/01-http-module': 'HTTP 模块',
    'backend/nodejs/http/02-create-server': '创建服务器',
    'backend/nodejs/http/03-routing': '路由处理',
    'backend/nodejs/http/04-middleware': '中间件概念',
    'backend/nodejs/express/01-intro': 'Express 简介',
    'backend/nodejs/express/02-routing': 'Express 路由',
    'backend/nodejs/express/03-middleware': 'Express 中间件',
    'backend/nodejs/express/04-request': '请求处理',
    'backend/nodejs/express/05-response': '响应处理',
    'backend/nodejs/express/06-static': '静态文件服务',
    'backend/nodejs/express/07-template': '模板引擎',
    'backend/nodejs/express/08-error-handling': '错误处理',
    'backend/nodejs/express/09-project-structure': '项目结构',
    'backend/nodejs/koa/01-intro': 'Koa 简介',
    'backend/nodejs/koa/02-middleware': 'Koa 中间件',
    'backend/nodejs/koa/03-context': 'Context 上下文',
    'backend/nodejs/koa/04-router': 'Koa Router',
    'backend/nodejs/nestjs/01-intro': 'NestJS 简介',
    'backend/nodejs/nestjs/02-modules': '模块',
    'backend/nodejs/nestjs/03-controllers': '控制器',
    'backend/nodejs/nestjs/04-providers': '提供者',
    'backend/nodejs/nestjs/05-dependency-injection': '依赖注入',
    'backend/nodejs/nestjs/06-pipes': '管道',
    'backend/nodejs/nestjs/07-guards': '守卫',
    'backend/nodejs/nestjs/08-interceptors': '拦截器',
    'backend/nodejs/nestjs/09-typeorm': 'TypeORM 集成',
})

# Node.js 数据库和认证
titles.update({
    'backend/nodejs/database/01-mysql-driver': 'MySQL 驱动',
    'backend/nodejs/database/02-mongodb-driver': 'MongoDB 驱动',
    'backend/nodejs/database/03-sequelize': 'Sequelize ORM',
    'backend/nodejs/database/04-prisma': 'Prisma ORM',
    'backend/nodejs/database/05-redis': 'Redis 客户端',
    'backend/nodejs/auth/01-session': 'Session 认证',
    'backend/nodejs/auth/02-jwt': 'JWT 认证',
    'backend/nodejs/auth/03-oauth': 'OAuth 2.0',
    'backend/nodejs/auth/04-passport': 'Passport.js',
    'backend/nodejs/advanced/01-cluster': '集群模式',
    'backend/nodejs/advanced/02-pm2': 'PM2 进程管理',
    'backend/nodejs/advanced/03-websocket': 'WebSocket',
    'backend/nodejs/advanced/04-graphql': 'GraphQL',
    'backend/nodejs/advanced/05-microservices': '微服务',
})

# Python
titles.update({
    'backend/python/basics/01-intro': 'Python 简介',
    'backend/python/basics/02-setup': 'Python 环境搭建',
    'backend/python/basics/03-syntax': 'Python 基础语法',
    'backend/python/basics/04-data-types': 'Python 数据类型',
    'backend/python/basics/05-control-flow': '流程控制',
    'backend/python/basics/06-functions': '函数',
    'backend/python/basics/07-modules': '模块与包',
    'backend/python/basics/08-oop': '面向对象编程',
    'backend/python/basics/09-exceptions': '异常处理',
    'backend/python/basics/10-file-io': '文件操作',
    'backend/python/advanced/01-decorators': '装饰器',
    'backend/python/advanced/02-generators': '生成器',
    'backend/python/advanced/03-context-managers': '上下文管理器',
    'backend/python/advanced/04-metaclasses': '元类',
    'backend/python/advanced/05-async': '异步编程',
    'backend/python/flask/01-intro': 'Flask 简介',
    'backend/python/flask/02-routing': 'Flask 路由',
    'backend/python/flask/03-templates': 'Jinja2 模板',
    'backend/python/flask/04-forms': '表单处理',
    'backend/python/flask/05-database': '数据库集成',
    'backend/python/flask/06-blueprints': '蓝图',
    'backend/python/flask/07-extensions': 'Flask 扩展',
    'backend/python/django/01-intro': 'Django 简介',
    'backend/python/django/02-project-setup': '项目创建',
    'backend/python/django/03-models': '模型',
    'backend/python/django/04-views': '视图',
    'backend/python/django/05-templates': '模板',
    'backend/python/django/06-urls': 'URL 配置',
    'backend/python/django/07-forms': '表单',
    'backend/python/django/08-admin': '管理后台',
    'backend/python/django/09-orm': 'Django ORM',
    'backend/python/django/10-auth': '用户认证',
    'backend/python/django/11-rest-framework': 'Django REST Framework',
    'backend/python/django/12-deployment': '部署',
    'backend/python/fastapi/01-intro': 'FastAPI 简介',
    'backend/python/fastapi/02-path-params': '路径参数',
    'backend/python/fastapi/03-query-params': '查询参数',
    'backend/python/fastapi/04-request-body': '请求体',
    'backend/python/fastapi/05-pydantic': 'Pydantic 模型',
    'backend/python/fastapi/06-dependency': '依赖注入',
    'backend/python/fastapi/07-security': '安全认证',
    'backend/python/fastapi/08-database': '数据库集成',
    'backend/python/fastapi/09-async': '异步处理',
    'backend/python/tools/01-pip': 'pip 包管理',
    'backend/python/tools/02-virtualenv': '虚拟环境',
    'backend/python/tools/03-poetry': 'Poetry',
    'backend/python/tools/04-pytest': 'pytest 测试',
})

# Go
titles.update({
    'backend/go/basics/01-intro': 'Go 语言简介',
    'backend/go/basics/02-setup': 'Go 环境搭建',
    'backend/go/basics/03-syntax': 'Go 基础语法',
    'backend/go/basics/04-data-types': 'Go 数据类型',
    'backend/go/basics/05-control-flow': '流程控制',
    'backend/go/basics/06-functions': '函数',
    'backend/go/basics/07-arrays-slices': '数组与切片',
    'backend/go/basics/08-maps': 'Map 映射',
    'backend/go/basics/09-structs': '结构体',
    'backend/go/basics/10-pointers': '指针',
    'backend/go/advanced/01-interfaces': '接口',
    'backend/go/advanced/02-methods': '方法',
    'backend/go/advanced/03-errors': '错误处理',
    'backend/go/advanced/04-goroutines': 'Goroutine 协程',
    'backend/go/advanced/05-channels': 'Channel 通道',
    'backend/go/advanced/06-select': 'Select 语句',
    'backend/go/advanced/07-sync': '同步原语',
    'backend/go/advanced/08-context': 'Context 上下文',
    'backend/go/advanced/09-reflection': '反射',
    'backend/go/gin/01-intro': 'Gin 框架简介',
    'backend/go/gin/02-routing': 'Gin 路由',
    'backend/go/gin/03-middleware': 'Gin 中间件',
    'backend/go/gin/04-request': '请求处理',
    'backend/go/gin/05-response': '响应处理',
    'backend/go/gin/06-validation': '数据验证',
    'backend/go/gin/07-project-structure': '项目结构',
    'backend/go/gorm/01-intro': 'GORM 简介',
    'backend/go/gorm/02-models': '模型定义',
    'backend/go/gorm/03-crud': 'CRUD 操作',
    'backend/go/gorm/04-associations': '关联关系',
    'backend/go/gorm/05-transactions': '事务',
    'backend/go/gorm/06-hooks': '钩子',
    'backend/go/tools/01-modules': 'Go Modules',
    'backend/go/tools/02-testing': 'Go 测试',
    'backend/go/tools/03-profiling': '性能分析',
})

# 架构
titles.update({
    'backend/architecture/design-patterns/01-intro': '设计模式概述',
    'backend/architecture/design-patterns/02-singleton': '单例模式',
    'backend/architecture/design-patterns/03-factory': '工厂模式',
    'backend/architecture/design-patterns/04-builder': '建造者模式',
    'backend/architecture/design-patterns/05-prototype': '原型模式',
    'backend/architecture/design-patterns/06-adapter': '适配器模式',
    'backend/architecture/design-patterns/07-decorator': '装饰器模式',
    'backend/architecture/design-patterns/08-proxy': '代理模式',
    'backend/architecture/design-patterns/09-observer': '观察者模式',
    'backend/architecture/design-patterns/10-strategy': '策略模式',
    'backend/architecture/design-patterns/11-template': '模板方法模式',
    'backend/architecture/microservices/01-intro': '微服务架构概述',
    'backend/architecture/microservices/02-service-split': '服务拆分',
    'backend/architecture/microservices/03-api-gateway': 'API 网关',
    'backend/architecture/microservices/04-service-discovery': '服务发现',
    'backend/architecture/microservices/05-load-balancing': '负载均衡',
    'backend/architecture/microservices/06-circuit-breaker': '熔断器',
    'backend/architecture/microservices/07-config-center': '配置中心',
    'backend/architecture/microservices/08-distributed-tracing': '分布式追踪',
    'backend/architecture/distributed/01-cap': 'CAP 理论',
    'backend/architecture/distributed/02-consistency': '一致性协议',
    'backend/architecture/distributed/03-distributed-lock': '分布式锁',
    'backend/architecture/distributed/04-distributed-id': '分布式 ID',
    'backend/architecture/distributed/05-distributed-tx': '分布式事务',
    'backend/architecture/high-availability/01-intro': '高可用架构概述',
    'backend/architecture/high-availability/02-redundancy': '冗余设计',
    'backend/architecture/high-availability/03-failover': '故障转移',
    'backend/architecture/high-availability/04-disaster-recovery': '灾难恢复',
    'backend/architecture/caching/01-intro': '缓存概述',
    'backend/architecture/caching/02-strategies': '缓存策略',
    'backend/architecture/caching/03-redis-cache': 'Redis 缓存',
    'backend/architecture/caching/04-local-cache': '本地缓存',
    'backend/architecture/caching/05-cache-problems': '缓存问题',
    'backend/architecture/message-queue/01-intro': '消息队列概述',
    'backend/architecture/message-queue/02-rabbitmq': 'RabbitMQ',
    'backend/architecture/message-queue/03-kafka': 'Kafka',
    'backend/architecture/message-queue/04-rocketmq': 'RocketMQ',
    'backend/architecture/message-queue/05-patterns': '消息模式',
})

# 数据库
titles.update({
    'database/basics/01-intro': '数据库概述',
    'database/basics/02-relational-vs-nosql': '关系型与 NoSQL',
    'database/basics/03-data-modeling': '数据建模',
    'database/basics/04-normalization': '数据库范式',
    'database/basics/05-er-diagram': 'ER 图设计',
    'database/sql/basics/01-intro': 'SQL 简介',
    'database/sql/basics/02-ddl': 'DDL 数据定义',
    'database/sql/basics/03-dml': 'DML 数据操作',
    'database/sql/basics/04-select': 'SELECT 查询',
    'database/sql/basics/05-where': 'WHERE 条件',
    'database/sql/basics/06-order-limit': 'ORDER BY 与 LIMIT',
    'database/sql/basics/07-aggregate': '聚合函数',
    'database/sql/basics/08-group-by': 'GROUP BY 分组',
    'database/sql/basics/09-distinct': 'DISTINCT 去重',
    'database/sql/joins/01-intro': 'JOIN 连接概述',
    'database/sql/joins/02-inner-join': 'INNER JOIN',
    'database/sql/joins/03-left-join': 'LEFT JOIN',
    'database/sql/joins/04-right-join': 'RIGHT JOIN',
    'database/sql/joins/05-full-join': 'FULL JOIN',
    'database/sql/joins/06-cross-join': 'CROSS JOIN',
    'database/sql/joins/07-self-join': '自连接',
    'database/sql/advanced/01-subqueries': '子查询',
    'database/sql/advanced/02-union': 'UNION 联合',
    'database/sql/advanced/03-case': 'CASE 表达式',
    'database/sql/advanced/04-window-functions': '窗口函数',
    'database/sql/advanced/05-cte': 'CTE 公共表表达式',
    'database/sql/advanced/06-views': '视图',
    'database/sql/advanced/07-stored-procedures': '存储过程',
    'database/sql/advanced/08-triggers': '触发器',
    'database/sql/advanced/09-transactions': '事务',
    'database/sql/practice/01-common-queries': '常用查询',
    'database/sql/practice/02-interview-questions': '面试题',
    'database/sql/practice/03-best-practices': '最佳实践',
})

# MySQL
titles.update({
    'database/mysql/basics/01-intro': 'MySQL 简介',
    'database/mysql/basics/02-installation': 'MySQL 安装',
    'database/mysql/basics/03-data-types': 'MySQL 数据类型',
    'database/mysql/basics/04-constraints': '约束',
    'database/mysql/basics/05-crud': 'CRUD 操作',
    'database/mysql/basics/06-functions': 'MySQL 函数',
    'database/mysql/index/01-intro': '索引概述',
    'database/mysql/index/02-btree': 'B+Tree 索引',
    'database/mysql/index/03-index-types': '索引类型',
    'database/mysql/index/04-composite-index': '复合索引',
    'database/mysql/index/05-covering-index': '覆盖索引',
    'database/mysql/index/06-index-optimization': '索引优化',
    'database/mysql/index/07-index-failure': '索引失效',
    'database/mysql/advanced/01-storage-engines': '存储引擎',
    'database/mysql/advanced/02-innodb': 'InnoDB 引擎',
    'database/mysql/advanced/03-locks': '锁机制',
    'database/mysql/advanced/04-mvcc': 'MVCC',
    'database/mysql/advanced/05-transaction-isolation': '事务隔离级别',
    'database/mysql/advanced/06-binlog': 'Binlog 日志',
    'database/mysql/advanced/07-replication': '主从复制',
    'database/mysql/optimization/01-explain': 'EXPLAIN 执行计划',
    'database/mysql/optimization/02-slow-query': '慢查询分析',
    'database/mysql/optimization/03-query-optimization': '查询优化',
    'database/mysql/optimization/04-table-optimization': '表优化',
    'database/mysql/optimization/05-configuration': '配置优化',
    'database/mysql/sharding/01-intro': '分库分表概述',
    'database/mysql/sharding/02-vertical': '垂直拆分',
    'database/mysql/sharding/03-horizontal': '水平拆分',
    'database/mysql/sharding/04-sharding-key': '分片键选择',
    'database/mysql/sharding/05-middleware': '分库分表中间件',
    'database/mysql/practice/01-backup-restore': '备份恢复',
    'database/mysql/practice/02-monitoring': '监控',
    'database/mysql/practice/03-troubleshooting': '故障排查',
})

# PostgreSQL, Redis, MongoDB, ES
titles.update({
    'database/postgresql/basics/01-intro': 'PostgreSQL 简介',
    'database/postgresql/basics/02-installation': 'PostgreSQL 安装',
    'database/postgresql/basics/03-data-types': 'PostgreSQL 数据类型',
    'database/postgresql/basics/04-crud': 'CRUD 操作',
    'database/postgresql/basics/05-psql': 'psql 命令行',
    'database/postgresql/advanced/01-json': 'JSON 数据类型',
    'database/postgresql/advanced/02-arrays': '数组类型',
    'database/postgresql/advanced/03-full-text-search': '全文搜索',
    'database/postgresql/advanced/04-partitioning': '分区表',
    'database/postgresql/advanced/05-inheritance': '表继承',
    'database/postgresql/advanced/06-extensions': '扩展',
    'database/postgresql/performance/01-explain': 'EXPLAIN 分析',
    'database/postgresql/performance/02-indexes': '索引优化',
    'database/postgresql/performance/03-vacuum': 'VACUUM 维护',
    'database/postgresql/replication/01-streaming': '流复制',
    'database/postgresql/replication/02-logical': '逻辑复制',
    'database/redis/basics/01-intro': 'Redis 简介',
    'database/redis/basics/02-installation': 'Redis 安装',
    'database/redis/basics/03-strings': 'String 字符串',
    'database/redis/basics/04-lists': 'List 列表',
    'database/redis/basics/05-sets': 'Set 集合',
    'database/redis/basics/06-hashes': 'Hash 哈希',
    'database/redis/basics/07-sorted-sets': 'Sorted Set 有序集合',
    'database/redis/basics/08-commands': '常用命令',
    'database/redis/advanced/01-pub-sub': '发布订阅',
    'database/redis/advanced/02-transactions': '事务',
    'database/redis/advanced/03-lua': 'Lua 脚本',
    'database/redis/advanced/04-streams': 'Streams',
    'database/redis/advanced/05-persistence': '持久化',
    'database/redis/advanced/06-memory': '内存管理',
    'database/redis/cluster/01-sentinel': 'Sentinel 哨兵',
    'database/redis/cluster/02-cluster': 'Redis Cluster',
    'database/redis/practice/01-caching': '缓存实践',
    'database/redis/practice/02-session': 'Session 存储',
    'database/redis/practice/03-rate-limiting': '限流',
    'database/redis/practice/04-distributed-lock': '分布式锁',
    'database/redis/practice/05-message-queue': '消息队列',
})

# MongoDB, ES
titles.update({
    'database/mongodb/basics/01-intro': 'MongoDB 简介',
    'database/mongodb/basics/02-installation': 'MongoDB 安装',
    'database/mongodb/basics/03-concepts': '核心概念',
    'database/mongodb/basics/04-crud': 'CRUD 操作',
    'database/mongodb/basics/05-query': '查询操作',
    'database/mongodb/basics/06-update': '更新操作',
    'database/mongodb/advanced/01-aggregation': '聚合管道',
    'database/mongodb/advanced/02-indexes': '索引',
    'database/mongodb/advanced/03-schema-design': 'Schema 设计',
    'database/mongodb/advanced/04-transactions': '事务',
    'database/mongodb/advanced/05-change-streams': 'Change Streams',
    'database/mongodb/replication/01-replica-set': '副本集',
    'database/mongodb/replication/02-sharding': '分片',
    'database/mongodb/practice/01-mongoose': 'Mongoose ODM',
    'database/mongodb/practice/02-best-practices': '最佳实践',
    'database/elasticsearch/basics/01-intro': 'Elasticsearch 简介',
    'database/elasticsearch/basics/02-installation': 'ES 安装配置',
    'database/elasticsearch/basics/03-concepts': '核心概念',
    'database/elasticsearch/basics/04-crud': 'CRUD 操作',
    'database/elasticsearch/basics/05-mapping': '映射',
    'database/elasticsearch/search/01-query-dsl': 'Query DSL',
    'database/elasticsearch/search/02-full-text': '全文搜索',
    'database/elasticsearch/search/03-term-queries': '精确查询',
    'database/elasticsearch/search/04-compound': '复合查询',
    'database/elasticsearch/search/05-aggregations': '聚合',
    'database/elasticsearch/search/06-highlighting': '高亮',
    'database/elasticsearch/advanced/01-analyzers': '分析器',
    'database/elasticsearch/advanced/02-chinese': '中文分词',
    'database/elasticsearch/advanced/03-index-templates': '索引模板',
    'database/elasticsearch/advanced/04-aliases': '别名',
    'database/elasticsearch/cluster/01-architecture': '集群架构',
    'database/elasticsearch/cluster/02-sharding': '分片策略',
})

# DevOps, AI, Mobile, Other
titles.update({
    'devops/git/workflow': 'Git 工作流',
    'devops/docker/basics': 'Docker 基础',
    'devops/docker/compose': 'Docker Compose',
    'devops/kubernetes/basics': 'Kubernetes 基础',
    'devops/kubernetes/istio': 'Istio 服务网格',
    'devops/ci-cd/jenkins': 'Jenkins',
    'devops/ci-cd/github-actions': 'GitHub Actions',
    'devops/ci-cd/gitlab-ci': 'GitLab CI',
    'devops/cloud/aws': 'AWS 云服务',
    'devops/cloud/aliyun': '阿里云',
    'devops/cloud/terraform': 'Terraform',
    'devops/monitor/prometheus': 'Prometheus 监控',
    'devops/monitor/grafana': 'Grafana 可视化',
    'devops/monitor/elk': 'ELK 日志系统',
    'ai/data/numpy': 'NumPy 数值计算',
    'ai/data/pandas': 'Pandas 数据分析',
    'ai/data/visualization': '数据可视化',
    'ai/data/tableau': 'Tableau',
    'ai/ml/basics': '机器学习基础',
    'ai/ml/supervised': '监督学习',
    'ai/ml/unsupervised': '无监督学习',
    'ai/ml/sklearn': 'Scikit-learn',
    'ai/dl/tensorflow': 'TensorFlow',
    'ai/dl/pytorch': 'PyTorch',
    'ai/dl/cnn': '卷积神经网络',
    'ai/dl/transformer': 'Transformer',
    'ai/bigdata/hadoop': 'Hadoop',
    'ai/bigdata/spark': 'Spark',
    'ai/bigdata/flink': 'Flink',
    'ai/bigdata/airflow': 'Airflow',
    'mobile/android/kotlin': 'Kotlin 语言',
    'mobile/android/sdk': 'Android SDK',
    'mobile/android/compose': 'Jetpack Compose',
    'mobile/ios/swift': 'Swift 语言',
    'mobile/ios/uikit': 'UIKit',
    'mobile/ios/swiftui': 'SwiftUI',
    'mobile/cross-platform/react-native': 'React Native',
    'mobile/cross-platform/flutter': 'Flutter',
    'mobile/cross-platform/uniapp': 'uni-app',
    'mobile/miniprogram/wechat': '微信小程序',
    'mobile/miniprogram/alipay': '支付宝小程序',
    'mobile/miniprogram/taro': 'Taro 跨端框架',
    'other/game/unity': 'Unity 游戏引擎',
    'other/game/unreal': 'Unreal Engine',
    'other/game/shader': 'Shader 编程',
    'other/blockchain/basics': '区块链基础',
    'other/blockchain/solidity': 'Solidity 智能合约',
    'other/blockchain/web3': 'Web3 开发',
    'other/security/basics': '安全基础',
    'other/security/web': 'Web 安全',
    'other/security/pentest': '渗透测试',
    'other/embedded/c-cpp': 'C/C++ 嵌入式',
    'other/embedded/stm32': 'STM32 开发',
    'other/embedded/freertos': 'FreeRTOS',
    'other/desktop/electron': 'Electron',
    'other/desktop/qt': 'Qt 框架',
    'other/desktop/flutter': 'Flutter Desktop',
})


def update_doc(filepath):
    """更新单个文档"""
    # 获取相对路径作为key
    rel_path = filepath.replace('docs/', '').replace('.md', '')
    title = titles.get(rel_path)
    
    if not title:
        # 尝试从文件名生成标题
        filename = os.path.basename(filepath).replace('.md', '')
        # 移除数字前缀
        title = re.sub(r'^\d+-', '', filename).replace('-', ' ').title()
    
    content = f'''# {title}

本章节将介绍 {title} 的相关内容。

## 学习目标

通过本章学习，你将掌握：

- {title} 的基本概念
- {title} 的核心用法
- {title} 的最佳实践

## 内容大纲

> 内容正在编写中...

'''
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Updated: {filepath}')

def main():
    docs_dir = 'docs'
    count = 0
    for root, dirs, files in os.walk(docs_dir):
        for file in files:
            if file.endswith('.md'):
                filepath = os.path.join(root, file).replace('\\', '/')
                update_doc(filepath)
                count += 1
    print(f'\nTotal updated: {count} files')

if __name__ == '__main__':
    main()
